name: pushchino_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  freezed: ^2.5.7
  http: ^1.2.2
  dio: ^5.7.0 
  meta: ^1.15.0
  bloc: ^8.1.4
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  open_file: ^3.5.10
  flutter_local_notifications: ^18.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoD.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login_page-bg/
    - assets/icons/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

